# Generated by Django 5.0 on 2024-09-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instituition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituitionName', models.CharField(max_length=40)),
                ('instituitionAddress', models.CharField(max_length=250)),
                ('instituitionLogo', models.ImageField(upload_to='')),
                ('instituitionNumber', models.IntegerField()),
                ('instituitionNumber2', models.IntegerField()),
                ('instituitionEmail', models.EmailField(max_length=254)),
                ('instituitionEmail2', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=25)),
                ('studentRollnumber', models.IntegerField()),
                ('studentNumber', models.IntegerField()),
                ('studentAddress1', models.CharField(max_length=50)),
                ('studentAddress2', models.CharField(max_length=50)),
                ('studentAddress3', models.CharField(max_length=50)),
                ('studentPhoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
