# Generated by Django 5.0 on 2024-10-12 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_app', '0002_rename_instituitionaddress_instituition_institutionaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sinstitution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='id_app.instituition'),
            preserve_default=False,
        ),
    ]
